### PR TITLE
Fix HTTP_HOST dependency in redirect function

### PR DESCRIPTION
**Pull request by anton-christensen**

### CODE REVIEW

**Comment by anton-christensen** [comment]
#GiMigMinTShirt

**Comment by hrjakobsen** [comment]
I'm not sure this is what we want. The reason for the HTTP_HOST is to not result in internal redirects. (see https://stackoverflow.com/a/1390754/5716947). Is the url changing in the browser with this PR?

**Comment by anton-christensen** [comment]
Try it out for yourself 
https://fklub.antonchristensen.net/cgi-bin/admin/index.cgi

**Comment by hrjakobsen** [comment]
image

**Comment by anton-christensen** [comment]
:(

**Comment by hrjakobsen** [comment]
Seems like the redirect is not working upon login

**Comment by hrjakobsen** [comment]
Implemented in #8 without `Location`

**Pull request closed without merging**
